version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: medai
      POSTGRES_PASSWORD: medai123
      POSTGRES_DB: medai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://medai:medai123@db:5432/medai_db
volumes:
  pgdata:
